Intial Commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,55 +1,60 @@
 version: 2.1
 
-orbs:    
-  slack: circleci/slack@4.12.0
 
+orbs:    
+  slack: circleci/slack@4.12.0 
 
 commands:
 
 
   install_awscli:
-      description: Install AWS CLI v2
-      steps:
-        - run:
-            name: Install AWS CLI v2
-            command: |
-              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-              unzip awscliv2.zip
-              sudo ./aws/install
-
-
-
-  install_ansible:
-      description: Install Ansible 
-      steps:
-        - run:
-            name: Install Ansible 
-            command: |  
-               sudo apt update
-               sudo apt install software-properties-common
-               sudo add-apt-repository --yes --update ppa:ansible/ansible
-               sudo apt install ansible -y
+    description: Install AWS CLI v2
+    steps:
+      - run:
+          name: Install AWS CLI v2
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
 
 
 
   install_nodejs:
-    description: Install Node.js 13
+
+    description: Install nodejs 13.8.0
     steps:
       - run:
-          name: Install Node.js 13
+          name: Install nodejs 
           command: |
+            #Install Node.js LTS version as our base Node.js version
             curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt install -y nodejs
+            sudo apt install -y nodejs  
+            #Use n version manager to use Node.js v13.8.0
             sudo npm install --global n
-            sudo n 13.8.0         
+            sudo n 13.8.0
+
+
+
+  install_ansible:
+    description: Install Ansible
+    steps:
+      - run:
+          name: Install Ansible
+          command: |
+            sudo apt update
+            sudo apt install software-properties-common -y
+            sudo add-apt-repository --yes --update ppa:ansible/ansible
+            sudo apt install ansible -y
 
 
   notify_on_failure:
     steps:
       - slack/notify:
           event: fail
-          channel: cicd-pipeline 
+          channel: uda-final-project 
           template: basic_fail_1
+
+
 
 
   destroy-environment:
@@ -66,6 +71,8 @@ commands:
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
             aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive 
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
+   
+
 
   revert-migrations:
     description: Revert the last migration
@@ -84,10 +91,11 @@ commands:
               cd ~/project/backend
               npm install
               npm run migrations:revert
-            fi
+            fi             
 
-            
 jobs:
+
+
 
   build-frontend:
     docker:
@@ -95,91 +103,98 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
-          name: Build front-end
+          name: Build Frontend
           command: |
             cd frontend
             npm install
             npm run build
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-deps
+          key: frontend-build
 
-      - notify_on_failure    
+      - notify_on_failure
 
- 
+
+
   build-backend:
     docker:
       - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-dpes]
+          keys: [backend-build]
       - run:
-          name: Back-end build
+          name: Build Backend
           command: |
              cd backend
              npm install
              npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-deps
+          key: backend-build
 
-      - notify_on_failure    
+      - notify_on_failure
 
- 
+
+
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
-          name: Front-end Unit Test
+          name: Test Frontend
           command: |
             cd frontend
             npm install
-            npm test
+            npm run test
 
-      - notify_on_failure          
- 
- 
+      - notify_on_failure
+
+
+
   test-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-dpes]
+          keys: [backend-build]
       - run:
-          name: Back-end Unit Test
+          name: Test Backend
           command: |
-             cd backend
-             npm install
-             npm test
+            cd backend
+            npm install
+            npm run test
 
-      - notify_on_failure      
- 
-  
+      - notify_on_failure
+
+
+            
   scan-frontend:
     docker:
       - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
-          name: Front-end Scan
+          name: Scan Frontend
           command: |
             cd frontend
             npm install
-            npm install oauth-sign@^0.9.0
-            npm audit fix --audit-level=critical
-            #npm audit --audit-level=critical
+            npm update loader-utils --depth 2
+            npm update minimist --depth 4
+            npm audit fix --audit-level=critical --force
+            npm audit --audit-level=critical
 
-      - notify_on_failure      
+      - notify_on_failure
+
+
 
 
   scan-backend:
@@ -188,18 +203,18 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-dpes]
+          keys: [backend-build]
       - run:
-          name: Back-end Scan
+          name: Scan Backend
           command: |
             cd backend
             npm install
-            #npm install oauth-sign@^0.9.0
-            npm audit fix --force --audit-level=critical
-            npm audit fix --force --audit-level=critical
-            #npm audit --audit-level=critical
+            npm audit fix --audit-level=critical --force
+            npm audit fix --audit-level=critical --force
+            npm audit --audit-level=critical
 
       - notify_on_failure
+
 
 
   deploy-infrastructure:
@@ -215,35 +230,36 @@ jobs:
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
-          
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+              
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              --tags project=your-tag \
+              --tags project=udapeople \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
-            
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+              
       - run:
           name: Add back-end ip to ansible inventory
           command: |
             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-             --output text)
-            echo $BACKEND_PUBLIC_IP>> .circleci\ansible\inventory.txt
-            cat .circleci\ansible\inventory.txt
-        
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+            echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
-            - project/.circleci/ansible/inventory.txt  
+            - project/.circleci/ansible/inventory.txt
 
-      - destroy-environment       
+      - destroy-environment
 
-  
+
+
+
   configure-infrastructure:
     docker:
       - image: cimg/base:stable
@@ -257,11 +273,13 @@ jobs:
       - run:
           name: Configure server
           command: |
-            cd .circleci/ansible
-            ansible-playbook -i inventory.txt configure-server.yml
-      
+              cd .circleci/ansible
+              ansible-playbook -i inventory.txt configure-server.yml
+
       - destroy-environment
-     
+ 
+
+
 
   run-migrations:
     docker:
@@ -288,8 +306,10 @@ jobs:
               curl -d '1' https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}
             fi 
       - destroy-environment
-      - revert-migrations       
-            
+      - revert-migrations
+
+
+
 
   deploy-frontend:
     docker:
@@ -322,9 +342,11 @@ jobs:
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
       
       - destroy-environment
-      - revert-migrations    
-                    
-  deploy-backend: 
+      - revert-migrations
+           
+
+
+  deploy-backend:
     docker:
       - image: cimg/base:stable
     steps:
@@ -335,38 +357,36 @@ jobs:
       - add_ssh_keys:
           fingerprints: ["7e:82:14:e8:c8:01:11:80:00:ca:08:f8:63:71:24:15"]
       - attach_workspace:
-          at: ~/
+          at: ~/ 
       - restore_cache:
-          keys: [backend-deps]
+          keys: [backend-build]
       - run:
           name: Install dependencies
           command: |
             cd backend
             npm install
       - run:
-          name: Package backend
-          command: |
+          name: Package Backend
+          command: |          
             cd backend
             npm run build
-            tar -czvf artifact.tar.gz dist/* package*
-
-            cd .. 
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files   
+            tar -czf artifact.tar.gz dist/* package*
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files/
+            
       - run:
           name: Deploy backend
           command: |
             export TYPEORM_MIGRATIONS_DIR=./migrations
             export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
             export TYPEORM_MIGRATIONS=./migrations/*.ts
-
             cd .circleci/ansible
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
-            
-      - destroy-environment   
-      - revert-migrations 
 
-
+      - destroy-environment
+      - revert-migrations
+    
 
   smoke-test:
     docker:
@@ -397,12 +417,13 @@ jobs:
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
-            else
               exit 1
+            else
+              exit 2
             fi 
       - destroy-environment 
-      - revert-migrations 
+      - revert-migrations
+
 
 
 
@@ -428,9 +449,10 @@ jobs:
   #             --template-file .circleci/files/cloudfront.yml \
   #             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
   #             --stack-name InitialStack
+
   #     - destroy-environment
   #     - revert-migrations
-
+       
 
 
   # cleanup:
@@ -455,7 +477,7 @@ jobs:
   #               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
   #               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
   #             fi
-            
+
 
 workflows:
   default:
@@ -474,7 +496,7 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
             branches:
-              only: [master]
+              only: [master]      
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
@@ -484,8 +506,10 @@ workflows:
       - deploy-backend:
           requires: [run-migrations]
       - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-#       - cloudfront-update:
-#           requires: [smoke-test]
-#       - cleanup:
-#           requires: [cloudfront-update]
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
+
+
